apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-t73v
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pkumari_org/multi-comp-e2e-nwnr-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-t73v@sha256:924ce431a54c2d137b77a3f0a5e0fc527d815a19e40346aefeb2ea73ec236d43
        name: my-go
        resources: {}
status: {}
