apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-daxc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pkumari_org/multi-comp-e2e-nwnr-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-daxc@sha256:992718e0a61d7fa53282d72fa2b3efb884b5c0251230f209a503c37264a5a5ca
        name: my-nodejs
        resources: {}
status: {}
